sources:
  b2b_center:
    base_url: https://www.b2b-center.ru
    enabled: true
    name: B2B-Center
    search_url: https://www.b2b-center.ru/market/
  gosplan:
    base_url: https://v2test.gosplan.info
    enabled: true
    name: ГосПлан API v2 (JSON)
    search_url: https://v2test.gosplan.info
  sberbank_ast:
    base_url: https://www.sberbank-ast.ru
    enabled: true
    name: Сбербанк-АСТ
    search_url: https://www.sberbank-ast.ru/UnitedPurchaseList.aspx
  zakupki:
    base_url: https://zakupki.gov.ru
    enabled: false
    name: ЕИС zakupki.gov.ru
    search_url: https://zakupki.gov.ru/epz/order/extendedsearch/results.html
